/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vistas;

import java.awt.Color;
import java.awt.Frame;
import javax.swing.ImageIcon;
import javax.swing.JFrame;

/**
 *
 * @author Marcos
 */
public class FrmPrincipal extends javax.swing.JFrame {

    private boolean agregarDepartamentoSelect = false;
    private boolean verDepartamentoSelect = false;
    private boolean agregarMunicipioSelect = false; 
    private boolean verMunicipioSelect = false; 
    private boolean agregarAfiliadoSelect = false; 
    private boolean verAfiliadoSelect = false;
    
    public FrmPrincipal() {
        initComponents();
        setLocationRelativeTo(null);
        setExtendedState(JFrame.MAXIMIZED_BOTH);
        getContentPane().setBackground(Color.white);
        pnlCapas1.setOpaque(true);
        pnlCapas1.setBackground(Color.white);
        pnlPrincipal.setOpaque(true);
        pnlPrincipal.setBackground(new Color(212, 212, 212));
        pnlAgregarDepartamento.setVisible(false);
        pnlVerDepartamento.setVisible(false);
        pnlAgregarMunicipio.setVisible(false);
        pnlVerMunicipio.setVisible(false);
        pnlAgregarAfiliado.setVisible(false);
        pnlVerInformacionAfiliado.setVisible(false);
        pnlBuscar.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        genero = new javax.swing.ButtonGroup();
        pnlCapas1 = new javax.swing.JLayeredPane();
        pnlVerInformacionAfiliado = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        pnlAgregarAfiliado = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        txtNombreAfiliado = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        jcbAgregarAfiliadoSeleccionarDepartamento = new javax.swing.JComboBox();
        jLabel23 = new javax.swing.JLabel();
        jcbAgregarAfiliadoSeleccionarMunicipio = new javax.swing.JComboBox();
        btnAgregarAfiliado = new javax.swing.JButton();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        rbtnHombre = new javax.swing.JRadioButton();
        rbtnMujer = new javax.swing.JRadioButton();
        jLabel26 = new javax.swing.JLabel();
        pnlVerMunicipio = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jcbVerMunicipioSeleccionarDepartamento = new javax.swing.JComboBox();
        jScrollPane5 = new javax.swing.JScrollPane();
        jTable5 = new javax.swing.JTable();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jcbVerMunicipioSeleccionarMunicipio = new javax.swing.JComboBox();
        pnlAgregarMunicipio = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        txtNombreMunicipio = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jcbAgregarMunicipioSeleccionarDepartamento = new javax.swing.JComboBox();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTable4 = new javax.swing.JTable();
        jLabel17 = new javax.swing.JLabel();
        btnAgregarMunicipio = new javax.swing.JButton();
        pnlVerDepartamento = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jcbVerDepartamentoSeleccionarDepartamento = new javax.swing.JComboBox();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable3 = new javax.swing.JTable();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        lblTotalAfiliadosDepartamento = new javax.swing.JLabel();
        pnlAgregarDepartamento = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        lblNombreDepartamento = new javax.swing.JLabel();
        txtNombreDepartamento = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jLabel11 = new javax.swing.JLabel();
        btnAgregarDepartamento = new javax.swing.JButton();
        pnlBuscar = new javax.swing.JPanel();
        lblBuscar = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        pnlPrincipal = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jcbBuscar = new javax.swing.JComboBox();
        txtBuscar = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        cmdAgregarDepartamento = new javax.swing.JLabel();
        cmdVerDepartamento = new javax.swing.JLabel();
        cmdAgregarMunicipio = new javax.swing.JLabel();
        cmdVerMunicipio = new javax.swing.JLabel();
        cmdAgregarAfiliado = new javax.swing.JLabel();
        cmdVerInformacion = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pnlCapas1.setBackground(new java.awt.Color(255, 0, 51));
        pnlCapas1.setForeground(new java.awt.Color(0, 204, 255));
        pnlCapas1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        pnlVerInformacionAfiliado.setBackground(new java.awt.Color(255, 255, 255));

        jLabel10.setFont(new java.awt.Font("Microsoft Tai Le", 0, 18)); // NOI18N
        jLabel10.setText("Información de ...");

        javax.swing.GroupLayout pnlVerInformacionAfiliadoLayout = new javax.swing.GroupLayout(pnlVerInformacionAfiliado);
        pnlVerInformacionAfiliado.setLayout(pnlVerInformacionAfiliadoLayout);
        pnlVerInformacionAfiliadoLayout.setHorizontalGroup(
            pnlVerInformacionAfiliadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlVerInformacionAfiliadoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel10)
                .addContainerGap(656, Short.MAX_VALUE))
        );
        pnlVerInformacionAfiliadoLayout.setVerticalGroup(
            pnlVerInformacionAfiliadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlVerInformacionAfiliadoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel10)
                .addContainerGap(464, Short.MAX_VALUE))
        );

        pnlAgregarAfiliado.setBackground(new java.awt.Color(255, 255, 255));

        jLabel9.setFont(new java.awt.Font("Microsoft Tai Le", 0, 18)); // NOI18N
        jLabel9.setText("Agregar Afiliado");

        jLabel21.setFont(new java.awt.Font("Microsoft Tai Le", 0, 14)); // NOI18N
        jLabel21.setText("Nombre");

        jLabel22.setFont(new java.awt.Font("Microsoft Tai Le", 0, 14)); // NOI18N
        jLabel22.setText("Departamento");

        jcbAgregarAfiliadoSeleccionarDepartamento.setFont(new java.awt.Font("Microsoft Tai Le", 0, 14)); // NOI18N

        jLabel23.setFont(new java.awt.Font("Microsoft Tai Le", 0, 14)); // NOI18N
        jLabel23.setText("Municipio");

        jcbAgregarAfiliadoSeleccionarMunicipio.setFont(new java.awt.Font("Microsoft Tai Le", 0, 14)); // NOI18N

        btnAgregarAfiliado.setBackground(new java.awt.Color(79, 105, 255));
        btnAgregarAfiliado.setFont(new java.awt.Font("Microsoft Tai Le", 0, 14)); // NOI18N
        btnAgregarAfiliado.setForeground(new java.awt.Color(255, 255, 255));
        btnAgregarAfiliado.setText("Agregar Afiliado");

        jLabel24.setFont(new java.awt.Font("Microsoft Tai Le", 0, 14)); // NOI18N
        jLabel24.setText("Fecha");

        jLabel25.setText("hoy ...");

        genero.add(rbtnHombre);
        rbtnHombre.setFont(new java.awt.Font("Microsoft Tai Le", 0, 14)); // NOI18N
        rbtnHombre.setText("Hombre");

        genero.add(rbtnMujer);
        rbtnMujer.setFont(new java.awt.Font("Microsoft Tai Le", 0, 14)); // NOI18N
        rbtnMujer.setText("Mujer");

        jLabel26.setFont(new java.awt.Font("Microsoft YaHei", 0, 14)); // NOI18N
        jLabel26.setText("Género");

        javax.swing.GroupLayout pnlAgregarAfiliadoLayout = new javax.swing.GroupLayout(pnlAgregarAfiliado);
        pnlAgregarAfiliado.setLayout(pnlAgregarAfiliadoLayout);
        pnlAgregarAfiliadoLayout.setHorizontalGroup(
            pnlAgregarAfiliadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlAgregarAfiliadoLayout.createSequentialGroup()
                .addGroup(pnlAgregarAfiliadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlAgregarAfiliadoLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(pnlAgregarAfiliadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlAgregarAfiliadoLayout.createSequentialGroup()
                                .addGroup(pnlAgregarAfiliadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(pnlAgregarAfiliadoLayout.createSequentialGroup()
                                        .addComponent(jLabel9)
                                        .addGap(116, 116, 116))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlAgregarAfiliadoLayout.createSequentialGroup()
                                        .addGroup(pnlAgregarAfiliadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel21)
                                            .addComponent(jLabel24))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                                .addGroup(pnlAgregarAfiliadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtNombreAfiliado, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel25)))
                            .addGroup(pnlAgregarAfiliadoLayout.createSequentialGroup()
                                .addGap(93, 93, 93)
                                .addComponent(jLabel22)
                                .addGap(128, 128, 128)
                                .addComponent(jLabel23)
                                .addGap(108, 108, 108)
                                .addComponent(jLabel26))))
                    .addGroup(pnlAgregarAfiliadoLayout.createSequentialGroup()
                        .addGap(70, 70, 70)
                        .addComponent(jcbAgregarAfiliadoSeleccionarDepartamento, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(47, 47, 47)
                        .addGroup(pnlAgregarAfiliadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlAgregarAfiliadoLayout.createSequentialGroup()
                                .addGap(17, 17, 17)
                                .addComponent(btnAgregarAfiliado))
                            .addGroup(pnlAgregarAfiliadoLayout.createSequentialGroup()
                                .addComponent(jcbAgregarAfiliadoSeleccionarMunicipio, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(42, 42, 42)
                                .addGroup(pnlAgregarAfiliadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(rbtnMujer)
                                    .addComponent(rbtnHombre))))))
                .addContainerGap(248, Short.MAX_VALUE))
        );
        pnlAgregarAfiliadoLayout.setVerticalGroup(
            pnlAgregarAfiliadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlAgregarAfiliadoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel9)
                .addGap(48, 48, 48)
                .addGroup(pnlAgregarAfiliadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel21)
                    .addComponent(txtNombreAfiliado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(pnlAgregarAfiliadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel24)
                    .addComponent(jLabel25))
                .addGroup(pnlAgregarAfiliadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlAgregarAfiliadoLayout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addGroup(pnlAgregarAfiliadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel23)
                            .addComponent(jLabel22))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(pnlAgregarAfiliadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jcbAgregarAfiliadoSeleccionarMunicipio, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jcbAgregarAfiliadoSeleccionarDepartamento, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(rbtnHombre)))
                    .addGroup(pnlAgregarAfiliadoLayout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(jLabel26)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rbtnMujer)
                .addGap(25, 25, 25)
                .addComponent(btnAgregarAfiliado)
                .addContainerGap(170, Short.MAX_VALUE))
        );

        pnlVerMunicipio.setBackground(new java.awt.Color(255, 255, 255));

        jLabel7.setFont(new java.awt.Font("Microsoft Tai Le", 0, 18)); // NOI18N
        jLabel7.setText("Ver Municipio");

        jLabel18.setFont(new java.awt.Font("Microsoft Tai Le", 0, 14)); // NOI18N
        jLabel18.setText("Seleccione Departamento al que pertence");

        jcbVerMunicipioSeleccionarDepartamento.setFont(new java.awt.Font("Microsoft Tai Le", 0, 14)); // NOI18N

        jTable5.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane5.setViewportView(jTable5);

        jLabel19.setFont(new java.awt.Font("Microsoft Tai Le", 0, 14)); // NOI18N
        jLabel19.setText("Afiliados en ...");

        jLabel20.setFont(new java.awt.Font("Microsoft Tai Le", 0, 14)); // NOI18N
        jLabel20.setText("Seleccione Municipio");

        jcbVerMunicipioSeleccionarMunicipio.setFont(new java.awt.Font("Microsoft Tai Le", 0, 14)); // NOI18N

        javax.swing.GroupLayout pnlVerMunicipioLayout = new javax.swing.GroupLayout(pnlVerMunicipio);
        pnlVerMunicipio.setLayout(pnlVerMunicipioLayout);
        pnlVerMunicipioLayout.setHorizontalGroup(
            pnlVerMunicipioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlVerMunicipioLayout.createSequentialGroup()
                .addGroup(pnlVerMunicipioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlVerMunicipioLayout.createSequentialGroup()
                        .addGroup(pnlVerMunicipioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlVerMunicipioLayout.createSequentialGroup()
                                .addGap(117, 117, 117)
                                .addGroup(pnlVerMunicipioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jcbVerMunicipioSeleccionarDepartamento, 0, 160, Short.MAX_VALUE)
                                    .addComponent(jcbVerMunicipioSeleccionarMunicipio, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(100, 100, 100))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlVerMunicipioLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel20)
                                .addGap(114, 114, 114)))
                        .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlVerMunicipioLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel7))
                    .addGroup(pnlVerMunicipioLayout.createSequentialGroup()
                        .addGap(72, 72, 72)
                        .addComponent(jLabel18)
                        .addGap(222, 222, 222)
                        .addComponent(jLabel19)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlVerMunicipioLayout.setVerticalGroup(
            pnlVerMunicipioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlVerMunicipioLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7)
                .addGap(32, 32, 32)
                .addGroup(pnlVerMunicipioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(jLabel19))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlVerMunicipioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlVerMunicipioLayout.createSequentialGroup()
                        .addComponent(jcbVerMunicipioSeleccionarDepartamento, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(66, 66, 66)
                        .addComponent(jLabel20)
                        .addGap(18, 18, 18)
                        .addComponent(jcbVerMunicipioSeleccionarMunicipio, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(257, Short.MAX_VALUE))
        );

        pnlAgregarMunicipio.setBackground(new java.awt.Color(255, 255, 255));

        jLabel6.setFont(new java.awt.Font("Microsoft Tai Le", 0, 18)); // NOI18N
        jLabel6.setText("Agregar Municipio");

        jLabel15.setFont(new java.awt.Font("Microsoft Tai Le", 0, 14)); // NOI18N
        jLabel15.setText("Nombre");

        jLabel16.setFont(new java.awt.Font("Microsoft Tai Le", 0, 14)); // NOI18N
        jLabel16.setText("Seleccione Departamento al que pertenece");

        jcbAgregarMunicipioSeleccionarDepartamento.setFont(new java.awt.Font("Microsoft Tai Le", 0, 14)); // NOI18N

        jTable4.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane4.setViewportView(jTable4);

        jLabel17.setFont(new java.awt.Font("Microsoft Tai Le", 0, 14)); // NOI18N
        jLabel17.setText("Municipios Existentes de ...");

        btnAgregarMunicipio.setBackground(new java.awt.Color(79, 105, 255));
        btnAgregarMunicipio.setFont(new java.awt.Font("Microsoft Tai Le", 0, 14)); // NOI18N
        btnAgregarMunicipio.setForeground(new java.awt.Color(255, 255, 255));
        btnAgregarMunicipio.setText("Agregar Municipio");

        javax.swing.GroupLayout pnlAgregarMunicipioLayout = new javax.swing.GroupLayout(pnlAgregarMunicipio);
        pnlAgregarMunicipio.setLayout(pnlAgregarMunicipioLayout);
        pnlAgregarMunicipioLayout.setHorizontalGroup(
            pnlAgregarMunicipioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlAgregarMunicipioLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6)
                .addGap(20, 20, 20))
            .addGroup(pnlAgregarMunicipioLayout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addGroup(pnlAgregarMunicipioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel16)
                    .addGroup(pnlAgregarMunicipioLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jcbAgregarMunicipioSeleccionarDepartamento, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(60, 60, 60)
                        .addComponent(jLabel15)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtNombreMunicipio, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnAgregarMunicipio))
                    .addComponent(jLabel17)
                    .addComponent(jScrollPane4))
                .addGap(0, 141, Short.MAX_VALUE))
        );
        pnlAgregarMunicipioLayout.setVerticalGroup(
            pnlAgregarMunicipioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlAgregarMunicipioLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6)
                .addGap(18, 18, 18)
                .addComponent(jLabel16)
                .addGap(18, 18, 18)
                .addGroup(pnlAgregarMunicipioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jcbAgregarMunicipioSeleccionarDepartamento, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15)
                    .addComponent(txtNombreMunicipio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAgregarMunicipio))
                .addGap(77, 77, 77)
                .addComponent(jLabel17)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 170, Short.MAX_VALUE)
                .addGap(99, 99, 99))
        );

        pnlVerDepartamento.setBackground(new java.awt.Color(255, 255, 255));

        jLabel4.setFont(new java.awt.Font("Microsoft Tai Le", 0, 18)); // NOI18N
        jLabel4.setText("Ver Departamento");

        jLabel12.setFont(new java.awt.Font("Microsoft Tai Le", 0, 14)); // NOI18N
        jLabel12.setText("Seleccionar Departamento");

        jcbVerDepartamentoSeleccionarDepartamento.setFont(new java.awt.Font("Microsoft Tai Le", 0, 14)); // NOI18N

        jTable3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(jTable3);

        jLabel13.setFont(new java.awt.Font("Microsoft Tai Le", 0, 14)); // NOI18N
        jLabel13.setText("Municipios de ...");

        jLabel14.setFont(new java.awt.Font("Microsoft Tai Le", 0, 14)); // NOI18N
        jLabel14.setText("Total afiliados en ...");

        lblTotalAfiliadosDepartamento.setFont(new java.awt.Font("Microsoft Tai Le", 0, 14)); // NOI18N
        lblTotalAfiliadosDepartamento.setText("jLabel15");

        javax.swing.GroupLayout pnlVerDepartamentoLayout = new javax.swing.GroupLayout(pnlVerDepartamento);
        pnlVerDepartamento.setLayout(pnlVerDepartamentoLayout);
        pnlVerDepartamentoLayout.setHorizontalGroup(
            pnlVerDepartamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlVerDepartamentoLayout.createSequentialGroup()
                .addGroup(pnlVerDepartamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlVerDepartamentoLayout.createSequentialGroup()
                        .addGap(487, 487, 487)
                        .addComponent(jLabel13))
                    .addGroup(pnlVerDepartamentoLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel4))
                    .addGroup(pnlVerDepartamentoLayout.createSequentialGroup()
                        .addGap(77, 77, 77)
                        .addGroup(pnlVerDepartamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jcbVerDepartamentoSeleccionarDepartamento, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(pnlVerDepartamentoLayout.createSequentialGroup()
                        .addGroup(pnlVerDepartamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlVerDepartamentoLayout.createSequentialGroup()
                                .addGap(95, 95, 95)
                                .addComponent(jLabel14))
                            .addGroup(pnlVerDepartamentoLayout.createSequentialGroup()
                                .addGap(123, 123, 123)
                                .addComponent(lblTotalAfiliadosDepartamento)))
                        .addGap(91, 91, 91)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlVerDepartamentoLayout.setVerticalGroup(
            pnlVerDepartamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlVerDepartamentoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addGap(30, 30, 30)
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jcbVerDepartamentoSeleccionarDepartamento, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addComponent(jLabel13)
                .addGap(18, 18, 18)
                .addGroup(pnlVerDepartamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 92, Short.MAX_VALUE)
                    .addGroup(pnlVerDepartamentoLayout.createSequentialGroup()
                        .addComponent(jLabel14)
                        .addGap(18, 18, 18)
                        .addComponent(lblTotalAfiliadosDepartamento)))
                .addGap(292, 292, 292))
        );

        pnlAgregarDepartamento.setBackground(new java.awt.Color(255, 255, 255));

        jLabel3.setFont(new java.awt.Font("Microsoft Tai Le", 0, 18)); // NOI18N
        jLabel3.setText("Agregar Departamento");

        lblNombreDepartamento.setFont(new java.awt.Font("Microsoft Tai Le", 0, 14)); // NOI18N
        lblNombreDepartamento.setText("Nombre: ");

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable2);

        jLabel11.setFont(new java.awt.Font("Microsoft Tai Le", 0, 14)); // NOI18N
        jLabel11.setText("Departamentos Existentes");

        btnAgregarDepartamento.setBackground(new java.awt.Color(79, 105, 255));
        btnAgregarDepartamento.setFont(new java.awt.Font("Microsoft Tai Le", 0, 14)); // NOI18N
        btnAgregarDepartamento.setForeground(new java.awt.Color(255, 255, 255));
        btnAgregarDepartamento.setText("Agregar Departamento");

        javax.swing.GroupLayout pnlAgregarDepartamentoLayout = new javax.swing.GroupLayout(pnlAgregarDepartamento);
        pnlAgregarDepartamento.setLayout(pnlAgregarDepartamentoLayout);
        pnlAgregarDepartamentoLayout.setHorizontalGroup(
            pnlAgregarDepartamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlAgregarDepartamentoLayout.createSequentialGroup()
                .addGroup(pnlAgregarDepartamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlAgregarDepartamentoLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel3))
                    .addGroup(pnlAgregarDepartamentoLayout.createSequentialGroup()
                        .addGap(103, 103, 103)
                        .addComponent(lblNombreDepartamento)
                        .addGap(18, 18, 18)
                        .addGroup(pnlAgregarDepartamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2)
                            .addGroup(pnlAgregarDepartamentoLayout.createSequentialGroup()
                                .addGroup(pnlAgregarDepartamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel11)
                                    .addGroup(pnlAgregarDepartamentoLayout.createSequentialGroup()
                                        .addComponent(txtNombreDepartamento, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(btnAgregarDepartamento)))
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addGap(196, 196, 196))
        );
        pnlAgregarDepartamentoLayout.setVerticalGroup(
            pnlAgregarDepartamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlAgregarDepartamentoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addGap(34, 34, 34)
                .addGroup(pnlAgregarDepartamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNombreDepartamento)
                    .addComponent(txtNombreDepartamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAgregarDepartamento))
                .addGap(57, 57, 57)
                .addComponent(jLabel11)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(290, Short.MAX_VALUE))
        );

        pnlBuscar.setBackground(new java.awt.Color(255, 255, 255));

        lblBuscar.setFont(new java.awt.Font("Microsoft Tai Le", 0, 18)); // NOI18N
        lblBuscar.setText("Buscando ...");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout pnlBuscarLayout = new javax.swing.GroupLayout(pnlBuscar);
        pnlBuscar.setLayout(pnlBuscarLayout);
        pnlBuscarLayout.setHorizontalGroup(
            pnlBuscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlBuscarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblBuscar)
                .addContainerGap(591, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlBuscarLayout.createSequentialGroup()
                .addContainerGap(169, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26))
        );
        pnlBuscarLayout.setVerticalGroup(
            pnlBuscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlBuscarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblBuscar)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 343, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(93, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout pnlCapas1Layout = new javax.swing.GroupLayout(pnlCapas1);
        pnlCapas1.setLayout(pnlCapas1Layout);
        pnlCapas1Layout.setHorizontalGroup(
            pnlCapas1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlBuscar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(pnlCapas1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(pnlAgregarDepartamento, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(pnlCapas1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(pnlVerDepartamento, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(pnlCapas1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(pnlAgregarMunicipio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(pnlCapas1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(pnlVerMunicipio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(pnlCapas1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(pnlAgregarAfiliado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(pnlCapas1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(pnlVerInformacionAfiliado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlCapas1Layout.setVerticalGroup(
            pnlCapas1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlBuscar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(pnlCapas1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(pnlAgregarDepartamento, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(pnlCapas1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(pnlVerDepartamento, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(pnlCapas1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(pnlAgregarMunicipio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(pnlCapas1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(pnlVerMunicipio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(pnlCapas1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(pnlAgregarAfiliado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(pnlCapas1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(pnlVerInformacionAfiliado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlCapas1.setLayer(pnlVerInformacionAfiliado, javax.swing.JLayeredPane.DEFAULT_LAYER);
        pnlCapas1.setLayer(pnlAgregarAfiliado, javax.swing.JLayeredPane.DEFAULT_LAYER);
        pnlCapas1.setLayer(pnlVerMunicipio, javax.swing.JLayeredPane.DEFAULT_LAYER);
        pnlCapas1.setLayer(pnlAgregarMunicipio, javax.swing.JLayeredPane.DEFAULT_LAYER);
        pnlCapas1.setLayer(pnlVerDepartamento, javax.swing.JLayeredPane.DEFAULT_LAYER);
        pnlCapas1.setLayer(pnlAgregarDepartamento, javax.swing.JLayeredPane.DEFAULT_LAYER);
        pnlCapas1.setLayer(pnlBuscar, javax.swing.JLayeredPane.DEFAULT_LAYER);

        pnlPrincipal.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                pnlPrincipalMousePressed(evt);
            }
        });

        jLabel1.setBackground(new java.awt.Color(225, 225, 225));
        jLabel1.setFont(new java.awt.Font("Microsoft Tai Le", 0, 16)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 102, 102));
        jLabel1.setText("Buscar");

        jcbBuscar.setFont(new java.awt.Font("Microsoft Tai Le", 0, 14)); // NOI18N
        jcbBuscar.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Por departamento", "Por municipio", "Hombres", "Mujeres" }));
        jcbBuscar.setBorder(null);
        jcbBuscar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jcbBuscarMousePressed(evt);
            }
        });

        txtBuscar.setFont(new java.awt.Font("Microsoft Tai Le", 0, 14)); // NOI18N
        txtBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBuscarActionPerformed(evt);
            }
        });
        txtBuscar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtBuscarKeyPressed(evt);
            }
        });

        jLabel2.setBackground(new java.awt.Color(225, 225, 225));
        jLabel2.setFont(new java.awt.Font("Microsoft Tai Le", 0, 16)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(102, 102, 102));
        jLabel2.setText("Departamentos");

        jLabel5.setBackground(new java.awt.Color(225, 225, 225));
        jLabel5.setFont(new java.awt.Font("Microsoft Tai Le", 0, 16)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(102, 102, 102));
        jLabel5.setText("Municipio");

        jLabel8.setBackground(new java.awt.Color(225, 225, 225));
        jLabel8.setFont(new java.awt.Font("Microsoft Tai Le", 0, 16)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(102, 102, 102));
        jLabel8.setText("Afiliados");

        cmdAgregarDepartamento.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/AgregarDepartamento.png"))); // NOI18N
        cmdAgregarDepartamento.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        cmdAgregarDepartamento.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                cmdAgregarDepartamentoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                cmdAgregarDepartamentoMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                cmdAgregarDepartamentoMousePressed(evt);
            }
        });

        cmdVerDepartamento.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/VerDepartamento.png"))); // NOI18N
        cmdVerDepartamento.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        cmdVerDepartamento.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                cmdVerDepartamentoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                cmdVerDepartamentoMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                cmdVerDepartamentoMousePressed(evt);
            }
        });

        cmdAgregarMunicipio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/AgregarMunicipio.png"))); // NOI18N
        cmdAgregarMunicipio.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        cmdAgregarMunicipio.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                cmdAgregarMunicipioMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                cmdAgregarMunicipioMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                cmdAgregarMunicipioMousePressed(evt);
            }
        });

        cmdVerMunicipio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/VerMunicipio.png"))); // NOI18N
        cmdVerMunicipio.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        cmdVerMunicipio.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                cmdVerMunicipioMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                cmdVerMunicipioMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                cmdVerMunicipioMousePressed(evt);
            }
        });

        cmdAgregarAfiliado.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/AgregarAfiliado.png"))); // NOI18N
        cmdAgregarAfiliado.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        cmdAgregarAfiliado.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                cmdAgregarAfiliadoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                cmdAgregarAfiliadoMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                cmdAgregarAfiliadoMousePressed(evt);
            }
        });

        cmdVerInformacion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/VerInformacion.png"))); // NOI18N
        cmdVerInformacion.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        cmdVerInformacion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                cmdVerInformacionMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                cmdVerInformacionMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                cmdVerInformacionMousePressed(evt);
            }
        });

        javax.swing.GroupLayout pnlPrincipalLayout = new javax.swing.GroupLayout(pnlPrincipal);
        pnlPrincipal.setLayout(pnlPrincipalLayout);
        pnlPrincipalLayout.setHorizontalGroup(
            pnlPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlPrincipalLayout.createSequentialGroup()
                .addGroup(pnlPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlPrincipalLayout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(pnlPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtBuscar)
                            .addComponent(jcbBuscar, 0, 260, Short.MAX_VALUE)))
                    .addGroup(pnlPrincipalLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(pnlPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel8)
                            .addComponent(jLabel5)
                            .addGroup(pnlPrincipalLayout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addGroup(pnlPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cmdVerDepartamento)
                                    .addComponent(cmdAgregarMunicipio)
                                    .addComponent(cmdAgregarDepartamento)
                                    .addComponent(cmdVerMunicipio)
                                    .addComponent(cmdAgregarAfiliado)
                                    .addComponent(cmdVerInformacion))))))
                .addContainerGap())
        );
        pnlPrincipalLayout.setVerticalGroup(
            pnlPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlPrincipalLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jcbBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cmdAgregarDepartamento)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cmdVerDepartamento)
                .addGap(40, 40, 40)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cmdAgregarMunicipio)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cmdVerMunicipio)
                .addGap(51, 51, 51)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cmdAgregarAfiliado)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cmdVerInformacion)
                .addContainerGap(43, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(pnlPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlCapas1))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlCapas1)
            .addComponent(pnlPrincipal, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBuscarActionPerformed
          
    }//GEN-LAST:event_txtBuscarActionPerformed

    private void cmdAgregarDepartamentoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cmdAgregarDepartamentoMouseEntered
        if(!agregarDepartamentoSelect)
        {
            ImageIcon icono = new ImageIcon(getClass().getResource("/Imagenes/AgregarDepartamentoHover.png"));
            cmdAgregarDepartamento.setIcon(icono);
        }
    }//GEN-LAST:event_cmdAgregarDepartamentoMouseEntered

    private void cmdAgregarDepartamentoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cmdAgregarDepartamentoMouseExited
        if(!agregarDepartamentoSelect)
        {
            ImageIcon icono = new ImageIcon(getClass().getResource("/Imagenes/AgregarDepartamento.png"));
            cmdAgregarDepartamento.setIcon(icono);
        }
    }//GEN-LAST:event_cmdAgregarDepartamentoMouseExited

    private void cmdVerDepartamentoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cmdVerDepartamentoMouseEntered
        if(!verDepartamentoSelect)
        {
            ImageIcon icono = new ImageIcon(getClass().getResource("/Imagenes/VerDepartamentoHover.png"));
            cmdVerDepartamento.setIcon(icono);
        }
    }//GEN-LAST:event_cmdVerDepartamentoMouseEntered

    private void cmdVerDepartamentoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cmdVerDepartamentoMouseExited
        if(!verDepartamentoSelect)
        {
            ImageIcon icono = new ImageIcon(getClass().getResource("/Imagenes/VerDepartamento.png"));
            cmdVerDepartamento.setIcon(icono);
        }
    }//GEN-LAST:event_cmdVerDepartamentoMouseExited

    private void cmdAgregarMunicipioMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cmdAgregarMunicipioMouseEntered
        if(!agregarMunicipioSelect)
        {
            ImageIcon icono = new ImageIcon(getClass().getResource("/Imagenes/AgregarMunicipioHover.png"));
            cmdAgregarMunicipio.setIcon(icono);
        }
    }//GEN-LAST:event_cmdAgregarMunicipioMouseEntered

    private void cmdAgregarMunicipioMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cmdAgregarMunicipioMouseExited
        if(!agregarMunicipioSelect)
        {
            ImageIcon icono = new ImageIcon(getClass().getResource("/Imagenes/AgregarMunicipio.png"));
            cmdAgregarMunicipio.setIcon(icono);
        }
    }//GEN-LAST:event_cmdAgregarMunicipioMouseExited

    private void cmdVerMunicipioMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cmdVerMunicipioMouseEntered
        if(!verMunicipioSelect)
        {
            ImageIcon icono = new ImageIcon(getClass().getResource("/Imagenes/VerMunicipioHover.png"));
            cmdVerMunicipio.setIcon(icono);
        }
    }//GEN-LAST:event_cmdVerMunicipioMouseEntered

    private void cmdVerMunicipioMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cmdVerMunicipioMouseExited
       if(!verMunicipioSelect)
       {
           ImageIcon icono = new ImageIcon(getClass().getResource("/Imagenes/VerMunicipio.png"));
           cmdVerMunicipio.setIcon(icono);
       }
    }//GEN-LAST:event_cmdVerMunicipioMouseExited

    private void cmdAgregarAfiliadoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cmdAgregarAfiliadoMouseEntered
        if(!agregarAfiliadoSelect)
        {
            ImageIcon icono = new ImageIcon(getClass().getResource("/Imagenes/AgregarAfiliadoHover.png"));
            cmdAgregarAfiliado.setIcon(icono);
        }
    }//GEN-LAST:event_cmdAgregarAfiliadoMouseEntered

    private void cmdAgregarAfiliadoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cmdAgregarAfiliadoMouseExited
       if(!agregarAfiliadoSelect)
       {
           ImageIcon icono = new ImageIcon(getClass().getResource("/Imagenes/AgregarAfiliado.png"));
           cmdAgregarAfiliado.setIcon(icono);
       }
    }//GEN-LAST:event_cmdAgregarAfiliadoMouseExited

    private void cmdVerInformacionMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cmdVerInformacionMouseEntered
        if(!verAfiliadoSelect)
        {
            ImageIcon icono = new ImageIcon(getClass().getResource("/Imagenes/VerInformacionHover.png"));
            cmdVerInformacion.setIcon(icono);
        }
    }//GEN-LAST:event_cmdVerInformacionMouseEntered

    private void cmdVerInformacionMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cmdVerInformacionMouseExited
        if(!verAfiliadoSelect)
        {
            ImageIcon icono = new ImageIcon(getClass().getResource("/Imagenes/VerInformacion.png"));
            cmdVerInformacion.setIcon(icono);
        }
    }//GEN-LAST:event_cmdVerInformacionMouseExited

    private void cmdAgregarDepartamentoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cmdAgregarDepartamentoMousePressed
        // asignacion de variables
        agregarDepartamentoSelect = true;
        verDepartamentoSelect = false;
        agregarMunicipioSelect = false; 
        verMunicipioSelect = false; 
        agregarAfiliadoSelect = false; 
        verAfiliadoSelect = false;
        
        // asignacion de iconos
        ImageIcon icono = new ImageIcon(getClass().getResource("/Imagenes/AgregarDepartamentoSelect.png"));
        cmdAgregarDepartamento.setIcon(icono);
        cmdVerDepartamento.setIcon(new ImageIcon(getClass().getResource("/Imagenes/VerDepartamento.png")));
        cmdAgregarMunicipio.setIcon(new ImageIcon(getClass().getResource("/Imagenes/AgregarMunicipio.png")));
        cmdVerMunicipio.setIcon(new ImageIcon(getClass().getResource("/Imagenes/VerMunicipio.png")));
        cmdAgregarAfiliado.setIcon(new ImageIcon(getClass().getResource("/Imagenes/AgregarAfiliado.png")));
        cmdVerInformacion.setIcon(new ImageIcon(getClass().getResource("/Imagenes/VerInformacion.png")));
        
    }//GEN-LAST:event_cmdAgregarDepartamentoMousePressed

    private void cmdVerDepartamentoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cmdVerDepartamentoMousePressed
        // asignacion de variables
        agregarDepartamentoSelect = false;
        verDepartamentoSelect = true;
        agregarMunicipioSelect = false; 
        verMunicipioSelect = false; 
        agregarAfiliadoSelect = false; 
        verAfiliadoSelect = false;
        
        // asignacion de iconos
        ImageIcon icono = new ImageIcon(getClass().getResource("/Imagenes/VerDepartamentoSelect.png"));
        cmdAgregarDepartamento.setIcon(new ImageIcon(getClass().getResource("/Imagenes/AgregarDepartamento.png")));
        cmdVerDepartamento.setIcon(icono);
        cmdAgregarMunicipio.setIcon(new ImageIcon(getClass().getResource("/Imagenes/AgregarMunicipio.png")));
        cmdVerMunicipio.setIcon(new ImageIcon(getClass().getResource("/Imagenes/VerMunicipio.png")));
        cmdAgregarAfiliado.setIcon(new ImageIcon(getClass().getResource("/Imagenes/AgregarAfiliado.png")));
        cmdVerInformacion.setIcon(new ImageIcon(getClass().getResource("/Imagenes/VerInformacion.png")));
    }//GEN-LAST:event_cmdVerDepartamentoMousePressed

    private void cmdAgregarMunicipioMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cmdAgregarMunicipioMousePressed
        // asignacion de variables
        agregarDepartamentoSelect = false;
        verDepartamentoSelect = false;
        agregarMunicipioSelect = true; 
        verMunicipioSelect = false; 
        agregarAfiliadoSelect = false; 
        verAfiliadoSelect = false;
        
        // asignacion de iconos
        ImageIcon icono = new ImageIcon(getClass().getResource("/Imagenes/AgregarMunicipioSelect.png"));
        cmdAgregarDepartamento.setIcon(new ImageIcon(getClass().getResource("/Imagenes/AgregarDepartamento.png")));
        cmdVerDepartamento.setIcon(new ImageIcon(getClass().getResource("/Imagenes/VerDepartamento.png")));
        cmdAgregarMunicipio.setIcon(icono);
        cmdVerMunicipio.setIcon(new ImageIcon(getClass().getResource("/Imagenes/VerMunicipio.png")));
        cmdAgregarAfiliado.setIcon(new ImageIcon(getClass().getResource("/Imagenes/AgregarAfiliado.png")));
        cmdVerInformacion.setIcon(new ImageIcon(getClass().getResource("/Imagenes/VerInformacion.png")));
    }//GEN-LAST:event_cmdAgregarMunicipioMousePressed

    private void cmdVerMunicipioMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cmdVerMunicipioMousePressed
        // asignacion de variables
        agregarDepartamentoSelect = false;
        verDepartamentoSelect = false;
        agregarMunicipioSelect = false; 
        verMunicipioSelect = true; 
        agregarAfiliadoSelect = false; 
        verAfiliadoSelect = false;
        
        // asignacion de iconos
        ImageIcon icono = new ImageIcon(getClass().getResource("/Imagenes/VerMunicipioSelect.png"));
        cmdAgregarDepartamento.setIcon(new ImageIcon(getClass().getResource("/Imagenes/AgregarDepartamento.png")));
        cmdVerDepartamento.setIcon(new ImageIcon(getClass().getResource("/Imagenes/VerDepartamento.png")));
        cmdAgregarMunicipio.setIcon(new ImageIcon(getClass().getResource("/Imagenes/AgregarMunicipio.png")));
        cmdVerMunicipio.setIcon(icono);
        cmdAgregarAfiliado.setIcon(new ImageIcon(getClass().getResource("/Imagenes/AgregarAfiliado.png")));
        cmdVerInformacion.setIcon(new ImageIcon(getClass().getResource("/Imagenes/VerInformacion.png")));
    }//GEN-LAST:event_cmdVerMunicipioMousePressed

    private void cmdAgregarAfiliadoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cmdAgregarAfiliadoMousePressed
        // asignacion de variables
        agregarDepartamentoSelect = false;
        verDepartamentoSelect = false;
        agregarMunicipioSelect = false; 
        verMunicipioSelect = false; 
        agregarAfiliadoSelect = true; 
        verAfiliadoSelect = false;
        
        // asignacion de iconos
        ImageIcon icono = new ImageIcon(getClass().getResource("/Imagenes/AgregarAfiliadoSelect.png"));
        cmdAgregarDepartamento.setIcon(new ImageIcon(getClass().getResource("/Imagenes/AgregarDepartamento.png")));
        cmdVerDepartamento.setIcon(new ImageIcon(getClass().getResource("/Imagenes/VerDepartamento.png")));
        cmdAgregarMunicipio.setIcon(new ImageIcon(getClass().getResource("/Imagenes/AgregarMunicipio.png")));
        cmdVerMunicipio.setIcon(new ImageIcon(getClass().getResource("/Imagenes/VerMunicipio.png")));
        cmdAgregarAfiliado.setIcon(icono);
        cmdVerInformacion.setIcon(new ImageIcon(getClass().getResource("/Imagenes/VerInformacion.png")));
    }//GEN-LAST:event_cmdAgregarAfiliadoMousePressed

    private void cmdVerInformacionMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cmdVerInformacionMousePressed
        // asignacion de variables
        agregarDepartamentoSelect = false;
        verDepartamentoSelect = false;
        agregarMunicipioSelect = false; 
        verMunicipioSelect = false; 
        agregarAfiliadoSelect = false; 
        verAfiliadoSelect = true;
        
        // asignacion de iconos
        ImageIcon icono = new ImageIcon(getClass().getResource("/Imagenes/VerInformacionSelect.png"));
        cmdAgregarDepartamento.setIcon(new ImageIcon(getClass().getResource("/Imagenes/AgregarDepartamento.png")));
        cmdVerDepartamento.setIcon(new ImageIcon(getClass().getResource("/Imagenes/VerDepartamento.png")));
        cmdAgregarMunicipio.setIcon(new ImageIcon(getClass().getResource("/Imagenes/AgregarMunicipio.png")));
        cmdVerMunicipio.setIcon(new ImageIcon(getClass().getResource("/Imagenes/VerMunicipio.png")));
        cmdAgregarAfiliado.setIcon(new ImageIcon(getClass().getResource("/Imagenes/AgregarAfiliado.png")));
        cmdVerInformacion.setIcon(icono);
    }//GEN-LAST:event_cmdVerInformacionMousePressed

    private void pnlPrincipalMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlPrincipalMousePressed
       
    }//GEN-LAST:event_pnlPrincipalMousePressed

    private void jcbBuscarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jcbBuscarMousePressed
        // asignacion de variables
        agregarDepartamentoSelect = false;
        verDepartamentoSelect = false;
        agregarMunicipioSelect = false; 
        verMunicipioSelect = false; 
        agregarAfiliadoSelect = false; 
        verAfiliadoSelect = false;
        
        // asignacion de iconos
        cmdAgregarDepartamento.setIcon(new ImageIcon(getClass().getResource("/Imagenes/AgregarDepartamento.png")));
        cmdVerDepartamento.setIcon(new ImageIcon(getClass().getResource("/Imagenes/VerDepartamento.png")));
        cmdAgregarMunicipio.setIcon(new ImageIcon(getClass().getResource("/Imagenes/AgregarMunicipio.png")));
        cmdVerMunicipio.setIcon(new ImageIcon(getClass().getResource("/Imagenes/VerMunicipio.png")));
        cmdAgregarAfiliado.setIcon(new ImageIcon(getClass().getResource("/Imagenes/AgregarAfiliado.png")));
        cmdVerInformacion.setIcon(new ImageIcon(getClass().getResource("/Imagenes/VerInformacion.png")));
    }//GEN-LAST:event_jcbBuscarMousePressed

    private void txtBuscarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBuscarKeyPressed
        // asignacion de variables
        agregarDepartamentoSelect = false;
        verDepartamentoSelect = false;
        agregarMunicipioSelect = false; 
        verMunicipioSelect = false; 
        agregarAfiliadoSelect = false; 
        verAfiliadoSelect = false;
        
        // asignacion de iconos
        cmdAgregarDepartamento.setIcon(new ImageIcon(getClass().getResource("/Imagenes/AgregarDepartamento.png")));
        cmdVerDepartamento.setIcon(new ImageIcon(getClass().getResource("/Imagenes/VerDepartamento.png")));
        cmdAgregarMunicipio.setIcon(new ImageIcon(getClass().getResource("/Imagenes/AgregarMunicipio.png")));
        cmdVerMunicipio.setIcon(new ImageIcon(getClass().getResource("/Imagenes/VerMunicipio.png")));
        cmdAgregarAfiliado.setIcon(new ImageIcon(getClass().getResource("/Imagenes/AgregarAfiliado.png")));
        cmdVerInformacion.setIcon(new ImageIcon(getClass().getResource("/Imagenes/VerInformacion.png")));
    }//GEN-LAST:event_txtBuscarKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnAgregarAfiliado;
    public javax.swing.JButton btnAgregarDepartamento;
    public javax.swing.JButton btnAgregarMunicipio;
    public javax.swing.JLabel cmdAgregarAfiliado;
    public javax.swing.JLabel cmdAgregarDepartamento;
    public javax.swing.JLabel cmdAgregarMunicipio;
    public javax.swing.JLabel cmdVerDepartamento;
    public javax.swing.JLabel cmdVerInformacion;
    public javax.swing.JLabel cmdVerMunicipio;
    private javax.swing.ButtonGroup genero;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    public javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    public javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTable jTable1;
    public javax.swing.JTable jTable2;
    private javax.swing.JTable jTable3;
    public javax.swing.JTable jTable4;
    private javax.swing.JTable jTable5;
    public javax.swing.JComboBox jcbAgregarAfiliadoSeleccionarDepartamento;
    public javax.swing.JComboBox jcbAgregarAfiliadoSeleccionarMunicipio;
    public javax.swing.JComboBox jcbAgregarMunicipioSeleccionarDepartamento;
    public javax.swing.JComboBox jcbBuscar;
    public javax.swing.JComboBox jcbVerDepartamentoSeleccionarDepartamento;
    public javax.swing.JComboBox jcbVerMunicipioSeleccionarDepartamento;
    public javax.swing.JComboBox jcbVerMunicipioSeleccionarMunicipio;
    public javax.swing.JLabel lblBuscar;
    private javax.swing.JLabel lblNombreDepartamento;
    private javax.swing.JLabel lblTotalAfiliadosDepartamento;
    public javax.swing.JPanel pnlAgregarAfiliado;
    public javax.swing.JPanel pnlAgregarDepartamento;
    public javax.swing.JPanel pnlAgregarMunicipio;
    public javax.swing.JPanel pnlBuscar;
    private javax.swing.JLayeredPane pnlCapas1;
    private javax.swing.JPanel pnlPrincipal;
    public javax.swing.JPanel pnlVerDepartamento;
    public javax.swing.JPanel pnlVerInformacionAfiliado;
    public javax.swing.JPanel pnlVerMunicipio;
    public javax.swing.JRadioButton rbtnHombre;
    public javax.swing.JRadioButton rbtnMujer;
    public javax.swing.JTextField txtBuscar;
    public javax.swing.JTextField txtNombreAfiliado;
    public javax.swing.JTextField txtNombreDepartamento;
    public javax.swing.JTextField txtNombreMunicipio;
    // End of variables declaration//GEN-END:variables
}
